# 手动运行: 编译 llvm linux-arm64-glibc
name: build linux-arm64-glibc

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest
    # 注: 直接编译失败, 需要 交叉编译
    #runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      # 安装依赖
      - run: |
          sudo apt-get update && \
          sudo apt-get -y install \
            llvm lld \
            binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross

      # 下载代码并编译
      - run: make clone-llvm

      # llvm: linux-arm64-glibc
      #- run: make build-linux-arm64
      - run: make build-linux-arm64-cross

      # 测试运行
      #- run: llvm-linux-arm64-glibc/llc --version

      - uses: actions/upload-artifact@v6
        with:
          name: llvm-linux-arm64-glibc
          path: llvm-linux-arm64-glibc
